//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Controls/PlayerCtrl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerCtrl : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerCtrl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerCtrl"",
    ""maps"": [
        {
            ""name"": ""GamePlay"",
            ""id"": ""9f1edee9-8cdd-482e-a645-56b99cb3c6b2"",
            ""actions"": [
                {
                    ""name"": ""ArrowsUp"",
                    ""type"": ""Button"",
                    ""id"": ""ba5b22e5-5df6-4315-b552-7efc1aa9f2ac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowDown"",
                    ""type"": ""Button"",
                    ""id"": ""82dc65b5-46d3-4d16-8dd1-426f57dace86"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""A"",
                    ""type"": ""Button"",
                    ""id"": ""3d52b18e-6287-437e-ae12-e63d291dc267"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowLeft"",
                    ""type"": ""Button"",
                    ""id"": ""3d95074c-3582-4bb8-ad35-2dd1f7e16f17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ArrowRight"",
                    ""type"": ""Button"",
                    ""id"": ""67217744-221c-45db-908b-adf29188eaff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""X"",
                    ""type"": ""Button"",
                    ""id"": ""007920bf-a868-4bbf-8ef7-6f0af8c98d89"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Y"",
                    ""type"": ""Button"",
                    ""id"": ""aeb92827-269a-4293-82a7-86bc56920694"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B"",
                    ""type"": ""Button"",
                    ""id"": ""bcbc9d2a-5d68-440c-a7fd-9d5ede4e13ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""232f9286-4d62-454b-8b84-88265a6ba6ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""edaaed92-ed59-44a9-bcbf-63a626950303"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R1"",
                    ""type"": ""Button"",
                    ""id"": ""d382a755-e6bd-4527-9d4a-a2f061b44460"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R2"",
                    ""type"": ""Button"",
                    ""id"": ""340a1c92-0396-4d09-bd54-1cdf81624d24"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L1"",
                    ""type"": ""Button"",
                    ""id"": ""e7c2fe79-0cad-4057-acca-aea22c674c0d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L2"",
                    ""type"": ""Button"",
                    ""id"": ""e13365ce-f222-46bc-b6ca-f553e7800372"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f109d92c-4889-498d-98e0-9ad273dd759a"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3f60178-24ec-4240-b903-c31e3af25e6b"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d450cf0a-3467-4ac2-8b24-4527831412d3"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""976496a5-ddf4-4d02-bac5-301195f6cd9a"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed76137e-9e78-460e-b0ff-53d4869063f2"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40d49846-5249-4016-9880-de4bf0145106"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8556d56c-dc6c-4c62-a974-abfa774ec164"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""675ce1ce-d037-4819-8abe-099d019dba73"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78b223f8-7a44-47a3-b3fa-1363466221d0"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70c9ac61-590b-4a1a-ada9-39689b3bc833"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99ef1e20-0558-4921-8e8d-650c503e4845"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2e35898-adb3-4c01-9780-f0c291194af3"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cef16f97-135e-4d73-b687-7e789cc3961e"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c8e9634-1488-4655-ad22-9f3832dbcb80"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Introduction"",
            ""id"": ""ce8ee36f-d127-44ac-a339-29c26391c4f7"",
            ""actions"": [
                {
                    ""name"": ""ArrowsUp"",
                    ""type"": ""Button"",
                    ""id"": ""f0f9a1f3-4f3b-4798-a703-f9daec993f17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowDown"",
                    ""type"": ""Button"",
                    ""id"": ""920991a6-2b7a-4d4c-8dcd-31a2194b8f57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""A"",
                    ""type"": ""Button"",
                    ""id"": ""a519385f-d13b-4881-8a3c-fec6a41e28d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowLeft"",
                    ""type"": ""Button"",
                    ""id"": ""7fa98901-4b22-497e-a3f8-678edc58cdaf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ArrowRight"",
                    ""type"": ""Button"",
                    ""id"": ""c91d0a77-622b-4a5d-98ee-f475b0da511e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""X"",
                    ""type"": ""Button"",
                    ""id"": ""075048df-4836-454d-99e1-a0e2476e9c1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Y"",
                    ""type"": ""Button"",
                    ""id"": ""e288a76b-a8ad-4f8a-a346-b093d53d464d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B"",
                    ""type"": ""Button"",
                    ""id"": ""886f5d2c-4ae7-402e-99ec-233193f87cbd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""717eead0-8ae1-4777-ae5b-4166dc3ebd15"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""95626c0c-6b46-4d18-9165-0c018fd8f714"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R1"",
                    ""type"": ""Button"",
                    ""id"": ""d9134842-6335-47f8-ab94-363243916ad5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R2"",
                    ""type"": ""Button"",
                    ""id"": ""47839f21-77df-4aaa-8b8a-1302c50b19bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L1"",
                    ""type"": ""Button"",
                    ""id"": ""653ab6c8-1104-4135-b62f-f727dbefbece"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L2"",
                    ""type"": ""Button"",
                    ""id"": ""ad1b6c90-443e-41d2-a30b-226f82537c7d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dfaa1128-b055-41b1-9b60-79b1a20833f7"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb3945fc-b762-40aa-8af6-472824ae2c99"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a619f12d-99e9-40a1-ac25-2e726bdbcca2"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21c005f1-d18f-424e-9bf9-1f3f3d67b6ca"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""419f770c-04e2-40c1-a3ed-a135ca6209eb"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bcf4ac79-547a-451f-9db5-9dea4b11bb8e"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7904c639-0c00-411d-ad7a-de35be49a926"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65578fce-ecf7-4ebb-bad7-f6baa6a5b87b"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3dcf3b6d-667d-4fd9-b628-b0182b0c67cb"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfe7f0ed-20a2-483e-96e0-b8b1232596f3"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""410c511f-9770-4705-a0d3-a37edfe7d851"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a50f1aa5-2344-49e4-a005-87e8dff6bbbc"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0eb6ff22-eefd-48dd-a4f1-93811e3fa8a6"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4306748b-080c-4283-a3a0-ab82c4dd7c92"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""a913d890-ea3e-4514-b1a3-5100f8d2b560"",
            ""actions"": [
                {
                    ""name"": ""ArrowsUp"",
                    ""type"": ""Button"",
                    ""id"": ""53f6dd8e-1c30-4eac-bcae-527b1819e0e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowDown"",
                    ""type"": ""Button"",
                    ""id"": ""7f914dc5-f60a-40db-b8ee-409112bc567d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""A"",
                    ""type"": ""Button"",
                    ""id"": ""98760232-c9ec-4d20-9c94-c317c07c9c20"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowLeft"",
                    ""type"": ""Button"",
                    ""id"": ""f39a2a1f-5bf4-419b-a38d-e9efee725e8f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ArrowRight"",
                    ""type"": ""Button"",
                    ""id"": ""9ec1d38d-f1cb-47c1-b67b-8b96238f5ba4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""X"",
                    ""type"": ""Button"",
                    ""id"": ""e3ab2448-078c-455f-aafa-984ef0e409fe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Y"",
                    ""type"": ""Button"",
                    ""id"": ""c19e3abc-0ae4-4097-aeea-1e3c4afe6aba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B"",
                    ""type"": ""Button"",
                    ""id"": ""598975c7-ee1c-4489-bc94-dfc9ceaf5573"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""cff52b95-8187-4e47-b6d2-390950e9f28c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""fa8d70ca-b471-439a-b62b-78c246e28189"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R1"",
                    ""type"": ""Button"",
                    ""id"": ""9dab8585-e2ba-4eb0-81d7-d69411a2825e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R2"",
                    ""type"": ""Button"",
                    ""id"": ""f29e2e9f-69d7-4e5c-9761-4fa291881d55"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L1"",
                    ""type"": ""Button"",
                    ""id"": ""08194fd6-0a15-4f1b-8a6a-af8afa9de7c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L2"",
                    ""type"": ""Button"",
                    ""id"": ""f0e637bf-3dc0-4f9c-ae7a-29f4dea8a0ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""912737fd-6ffc-4268-8d40-e400f4c91767"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""decb5bc7-af3a-4a2e-ab5b-852d2451156b"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd4b01de-21dc-4fae-85ff-851258698178"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb015d14-37d8-42cc-ae33-351c94026fb5"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4428a260-f6a3-4178-b11a-14603a15c812"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76942fb8-b36b-4661-9db8-3f18240e2bca"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41cde104-82b3-4196-8eca-65d3b950ac22"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba65862a-f7b7-4e06-a58e-646f41b82d28"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1990955c-99b5-45b6-83e6-4be4a6267554"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8dfdd282-2439-4b54-8997-6c0cd66bfceb"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""119f9b49-95d7-49cc-bcd6-19ad1436d724"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0cad8f1f-28fd-486c-92e9-58ab2ba3ec32"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1f382ee-7038-41f4-b558-03bbe7521aa1"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7818e03b-cdf3-4647-9c5b-13b0acc6d5ec"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""EditingMap"",
            ""id"": ""295de605-6269-4151-a5df-26d724a2fa1e"",
            ""actions"": [
                {
                    ""name"": ""ArrowsUp"",
                    ""type"": ""Button"",
                    ""id"": ""1abee0e5-568b-407e-819d-3900e3267901"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowDown"",
                    ""type"": ""Button"",
                    ""id"": ""80506686-e43c-4b9c-a039-92cd83d0e14c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""A"",
                    ""type"": ""Button"",
                    ""id"": ""ed9b8b50-301d-42c7-8039-1d336418d34d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowLeft"",
                    ""type"": ""Button"",
                    ""id"": ""e19c6458-7cc1-4381-a8ad-992e57477c14"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ArrowRight"",
                    ""type"": ""Button"",
                    ""id"": ""195eb4cf-a07e-4dcc-a3b1-cb2bc182ca1c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""X"",
                    ""type"": ""Button"",
                    ""id"": ""e1acde34-fedf-478a-aa64-46e419a9c588"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Y"",
                    ""type"": ""Button"",
                    ""id"": ""fc7d8d45-70c7-4cd0-a60e-22283e0c114c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B"",
                    ""type"": ""Button"",
                    ""id"": ""41557bbf-18ec-4d33-a601-bf267dfefdf4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""70588a2a-22db-4d47-b9e4-01430c5e4e7f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""74f1d8f4-0a1b-429c-9623-cd739039b7a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R1"",
                    ""type"": ""Button"",
                    ""id"": ""0d703be8-bdab-43a7-9c09-f4465f282491"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R2"",
                    ""type"": ""Button"",
                    ""id"": ""91631375-e20f-4a03-a2b6-7c0103331c77"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L1"",
                    ""type"": ""Button"",
                    ""id"": ""05a4cd42-e671-4dc1-af43-ad5fd2df745e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L2"",
                    ""type"": ""Button"",
                    ""id"": ""9a3e5c62-552f-4eb2-9aba-11a9d5e5c7f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f35fd70b-afae-438c-ba2b-ddd6146095e4"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowsUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b58695a0-d3ce-4b92-bf03-790e7c7f321a"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""661dddce-d853-4f29-9dd2-7224ce528ae7"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9220ced6-fc0b-41c9-a712-aa3b613bb16b"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6196fbbb-9bac-4cfa-b5a7-5c689f0b1a7e"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c17ccb2-1909-453d-8d6b-bc58aefa3789"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7963dc0c-f0e5-4b5e-b885-62e358dd02ab"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51e01c5e-1f3c-4ae0-8b77-5e3c0d4a4a96"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e17cd694-bd81-4922-8c55-297124b8d808"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e435432-ffd6-4951-8235-37c598989d24"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3bdde4d5-21b0-4476-9b2a-ab390191c153"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28ee067f-63fe-4978-8c94-4d44414ecdbd"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb7f03c4-c944-4093-b117-191fd94573f6"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9237231-64b2-4eb0-961a-a1ef0660c03e"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""No Controls"",
            ""id"": ""cbee98ac-b9bf-4e7f-8614-e2abc101bc60"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""0acaf016-a425-40e9-a9a3-eeff5b67adde"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c96b1e28-965b-4b21-b376-05d0d36cc831"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GamePlay
        m_GamePlay = asset.FindActionMap("GamePlay", throwIfNotFound: true);
        m_GamePlay_ArrowsUp = m_GamePlay.FindAction("ArrowsUp", throwIfNotFound: true);
        m_GamePlay_ArrowDown = m_GamePlay.FindAction("ArrowDown", throwIfNotFound: true);
        m_GamePlay_A = m_GamePlay.FindAction("A", throwIfNotFound: true);
        m_GamePlay_ArrowLeft = m_GamePlay.FindAction("ArrowLeft", throwIfNotFound: true);
        m_GamePlay_ArrowRight = m_GamePlay.FindAction("ArrowRight", throwIfNotFound: true);
        m_GamePlay_X = m_GamePlay.FindAction("X", throwIfNotFound: true);
        m_GamePlay_Y = m_GamePlay.FindAction("Y", throwIfNotFound: true);
        m_GamePlay_B = m_GamePlay.FindAction("B", throwIfNotFound: true);
        m_GamePlay_Start = m_GamePlay.FindAction("Start", throwIfNotFound: true);
        m_GamePlay_Select = m_GamePlay.FindAction("Select", throwIfNotFound: true);
        m_GamePlay_R1 = m_GamePlay.FindAction("R1", throwIfNotFound: true);
        m_GamePlay_R2 = m_GamePlay.FindAction("R2", throwIfNotFound: true);
        m_GamePlay_L1 = m_GamePlay.FindAction("L1", throwIfNotFound: true);
        m_GamePlay_L2 = m_GamePlay.FindAction("L2", throwIfNotFound: true);
        // Introduction
        m_Introduction = asset.FindActionMap("Introduction", throwIfNotFound: true);
        m_Introduction_ArrowsUp = m_Introduction.FindAction("ArrowsUp", throwIfNotFound: true);
        m_Introduction_ArrowDown = m_Introduction.FindAction("ArrowDown", throwIfNotFound: true);
        m_Introduction_A = m_Introduction.FindAction("A", throwIfNotFound: true);
        m_Introduction_ArrowLeft = m_Introduction.FindAction("ArrowLeft", throwIfNotFound: true);
        m_Introduction_ArrowRight = m_Introduction.FindAction("ArrowRight", throwIfNotFound: true);
        m_Introduction_X = m_Introduction.FindAction("X", throwIfNotFound: true);
        m_Introduction_Y = m_Introduction.FindAction("Y", throwIfNotFound: true);
        m_Introduction_B = m_Introduction.FindAction("B", throwIfNotFound: true);
        m_Introduction_Start = m_Introduction.FindAction("Start", throwIfNotFound: true);
        m_Introduction_Select = m_Introduction.FindAction("Select", throwIfNotFound: true);
        m_Introduction_R1 = m_Introduction.FindAction("R1", throwIfNotFound: true);
        m_Introduction_R2 = m_Introduction.FindAction("R2", throwIfNotFound: true);
        m_Introduction_L1 = m_Introduction.FindAction("L1", throwIfNotFound: true);
        m_Introduction_L2 = m_Introduction.FindAction("L2", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_ArrowsUp = m_UI.FindAction("ArrowsUp", throwIfNotFound: true);
        m_UI_ArrowDown = m_UI.FindAction("ArrowDown", throwIfNotFound: true);
        m_UI_A = m_UI.FindAction("A", throwIfNotFound: true);
        m_UI_ArrowLeft = m_UI.FindAction("ArrowLeft", throwIfNotFound: true);
        m_UI_ArrowRight = m_UI.FindAction("ArrowRight", throwIfNotFound: true);
        m_UI_X = m_UI.FindAction("X", throwIfNotFound: true);
        m_UI_Y = m_UI.FindAction("Y", throwIfNotFound: true);
        m_UI_B = m_UI.FindAction("B", throwIfNotFound: true);
        m_UI_Start = m_UI.FindAction("Start", throwIfNotFound: true);
        m_UI_Select = m_UI.FindAction("Select", throwIfNotFound: true);
        m_UI_R1 = m_UI.FindAction("R1", throwIfNotFound: true);
        m_UI_R2 = m_UI.FindAction("R2", throwIfNotFound: true);
        m_UI_L1 = m_UI.FindAction("L1", throwIfNotFound: true);
        m_UI_L2 = m_UI.FindAction("L2", throwIfNotFound: true);
        // EditingMap
        m_EditingMap = asset.FindActionMap("EditingMap", throwIfNotFound: true);
        m_EditingMap_ArrowsUp = m_EditingMap.FindAction("ArrowsUp", throwIfNotFound: true);
        m_EditingMap_ArrowDown = m_EditingMap.FindAction("ArrowDown", throwIfNotFound: true);
        m_EditingMap_A = m_EditingMap.FindAction("A", throwIfNotFound: true);
        m_EditingMap_ArrowLeft = m_EditingMap.FindAction("ArrowLeft", throwIfNotFound: true);
        m_EditingMap_ArrowRight = m_EditingMap.FindAction("ArrowRight", throwIfNotFound: true);
        m_EditingMap_X = m_EditingMap.FindAction("X", throwIfNotFound: true);
        m_EditingMap_Y = m_EditingMap.FindAction("Y", throwIfNotFound: true);
        m_EditingMap_B = m_EditingMap.FindAction("B", throwIfNotFound: true);
        m_EditingMap_Start = m_EditingMap.FindAction("Start", throwIfNotFound: true);
        m_EditingMap_Select = m_EditingMap.FindAction("Select", throwIfNotFound: true);
        m_EditingMap_R1 = m_EditingMap.FindAction("R1", throwIfNotFound: true);
        m_EditingMap_R2 = m_EditingMap.FindAction("R2", throwIfNotFound: true);
        m_EditingMap_L1 = m_EditingMap.FindAction("L1", throwIfNotFound: true);
        m_EditingMap_L2 = m_EditingMap.FindAction("L2", throwIfNotFound: true);
        // No Controls
        m_NoControls = asset.FindActionMap("No Controls", throwIfNotFound: true);
        m_NoControls_Newaction = m_NoControls.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GamePlay
    private readonly InputActionMap m_GamePlay;
    private IGamePlayActions m_GamePlayActionsCallbackInterface;
    private readonly InputAction m_GamePlay_ArrowsUp;
    private readonly InputAction m_GamePlay_ArrowDown;
    private readonly InputAction m_GamePlay_A;
    private readonly InputAction m_GamePlay_ArrowLeft;
    private readonly InputAction m_GamePlay_ArrowRight;
    private readonly InputAction m_GamePlay_X;
    private readonly InputAction m_GamePlay_Y;
    private readonly InputAction m_GamePlay_B;
    private readonly InputAction m_GamePlay_Start;
    private readonly InputAction m_GamePlay_Select;
    private readonly InputAction m_GamePlay_R1;
    private readonly InputAction m_GamePlay_R2;
    private readonly InputAction m_GamePlay_L1;
    private readonly InputAction m_GamePlay_L2;
    public struct GamePlayActions
    {
        private @PlayerCtrl m_Wrapper;
        public GamePlayActions(@PlayerCtrl wrapper) { m_Wrapper = wrapper; }
        public InputAction @ArrowsUp => m_Wrapper.m_GamePlay_ArrowsUp;
        public InputAction @ArrowDown => m_Wrapper.m_GamePlay_ArrowDown;
        public InputAction @A => m_Wrapper.m_GamePlay_A;
        public InputAction @ArrowLeft => m_Wrapper.m_GamePlay_ArrowLeft;
        public InputAction @ArrowRight => m_Wrapper.m_GamePlay_ArrowRight;
        public InputAction @X => m_Wrapper.m_GamePlay_X;
        public InputAction @Y => m_Wrapper.m_GamePlay_Y;
        public InputAction @B => m_Wrapper.m_GamePlay_B;
        public InputAction @Start => m_Wrapper.m_GamePlay_Start;
        public InputAction @Select => m_Wrapper.m_GamePlay_Select;
        public InputAction @R1 => m_Wrapper.m_GamePlay_R1;
        public InputAction @R2 => m_Wrapper.m_GamePlay_R2;
        public InputAction @L1 => m_Wrapper.m_GamePlay_L1;
        public InputAction @L2 => m_Wrapper.m_GamePlay_L2;
        public InputActionMap Get() { return m_Wrapper.m_GamePlay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamePlayActions set) { return set.Get(); }
        public void SetCallbacks(IGamePlayActions instance)
        {
            if (m_Wrapper.m_GamePlayActionsCallbackInterface != null)
            {
                @ArrowsUp.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnArrowsUp;
                @ArrowsUp.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnArrowsUp;
                @ArrowsUp.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnArrowsUp;
                @ArrowDown.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnArrowDown;
                @ArrowDown.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnArrowDown;
                @ArrowDown.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnArrowDown;
                @A.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnA;
                @A.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnA;
                @A.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnA;
                @ArrowLeft.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnArrowLeft;
                @ArrowLeft.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnArrowLeft;
                @ArrowLeft.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnArrowLeft;
                @ArrowRight.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnArrowRight;
                @ArrowRight.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnArrowRight;
                @ArrowRight.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnArrowRight;
                @X.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnX;
                @X.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnX;
                @X.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnX;
                @Y.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnY;
                @Y.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnY;
                @Y.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnY;
                @B.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnB;
                @B.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnB;
                @B.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnB;
                @Start.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnStart;
                @Start.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnStart;
                @Start.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnStart;
                @Select.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnSelect;
                @R1.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnR1;
                @R1.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnR1;
                @R1.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnR1;
                @R2.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnR2;
                @R2.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnR2;
                @R2.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnR2;
                @L1.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnL1;
                @L1.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnL1;
                @L1.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnL1;
                @L2.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnL2;
                @L2.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnL2;
                @L2.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnL2;
            }
            m_Wrapper.m_GamePlayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ArrowsUp.started += instance.OnArrowsUp;
                @ArrowsUp.performed += instance.OnArrowsUp;
                @ArrowsUp.canceled += instance.OnArrowsUp;
                @ArrowDown.started += instance.OnArrowDown;
                @ArrowDown.performed += instance.OnArrowDown;
                @ArrowDown.canceled += instance.OnArrowDown;
                @A.started += instance.OnA;
                @A.performed += instance.OnA;
                @A.canceled += instance.OnA;
                @ArrowLeft.started += instance.OnArrowLeft;
                @ArrowLeft.performed += instance.OnArrowLeft;
                @ArrowLeft.canceled += instance.OnArrowLeft;
                @ArrowRight.started += instance.OnArrowRight;
                @ArrowRight.performed += instance.OnArrowRight;
                @ArrowRight.canceled += instance.OnArrowRight;
                @X.started += instance.OnX;
                @X.performed += instance.OnX;
                @X.canceled += instance.OnX;
                @Y.started += instance.OnY;
                @Y.performed += instance.OnY;
                @Y.canceled += instance.OnY;
                @B.started += instance.OnB;
                @B.performed += instance.OnB;
                @B.canceled += instance.OnB;
                @Start.started += instance.OnStart;
                @Start.performed += instance.OnStart;
                @Start.canceled += instance.OnStart;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @R1.started += instance.OnR1;
                @R1.performed += instance.OnR1;
                @R1.canceled += instance.OnR1;
                @R2.started += instance.OnR2;
                @R2.performed += instance.OnR2;
                @R2.canceled += instance.OnR2;
                @L1.started += instance.OnL1;
                @L1.performed += instance.OnL1;
                @L1.canceled += instance.OnL1;
                @L2.started += instance.OnL2;
                @L2.performed += instance.OnL2;
                @L2.canceled += instance.OnL2;
            }
        }
    }
    public GamePlayActions @GamePlay => new GamePlayActions(this);

    // Introduction
    private readonly InputActionMap m_Introduction;
    private IIntroductionActions m_IntroductionActionsCallbackInterface;
    private readonly InputAction m_Introduction_ArrowsUp;
    private readonly InputAction m_Introduction_ArrowDown;
    private readonly InputAction m_Introduction_A;
    private readonly InputAction m_Introduction_ArrowLeft;
    private readonly InputAction m_Introduction_ArrowRight;
    private readonly InputAction m_Introduction_X;
    private readonly InputAction m_Introduction_Y;
    private readonly InputAction m_Introduction_B;
    private readonly InputAction m_Introduction_Start;
    private readonly InputAction m_Introduction_Select;
    private readonly InputAction m_Introduction_R1;
    private readonly InputAction m_Introduction_R2;
    private readonly InputAction m_Introduction_L1;
    private readonly InputAction m_Introduction_L2;
    public struct IntroductionActions
    {
        private @PlayerCtrl m_Wrapper;
        public IntroductionActions(@PlayerCtrl wrapper) { m_Wrapper = wrapper; }
        public InputAction @ArrowsUp => m_Wrapper.m_Introduction_ArrowsUp;
        public InputAction @ArrowDown => m_Wrapper.m_Introduction_ArrowDown;
        public InputAction @A => m_Wrapper.m_Introduction_A;
        public InputAction @ArrowLeft => m_Wrapper.m_Introduction_ArrowLeft;
        public InputAction @ArrowRight => m_Wrapper.m_Introduction_ArrowRight;
        public InputAction @X => m_Wrapper.m_Introduction_X;
        public InputAction @Y => m_Wrapper.m_Introduction_Y;
        public InputAction @B => m_Wrapper.m_Introduction_B;
        public InputAction @Start => m_Wrapper.m_Introduction_Start;
        public InputAction @Select => m_Wrapper.m_Introduction_Select;
        public InputAction @R1 => m_Wrapper.m_Introduction_R1;
        public InputAction @R2 => m_Wrapper.m_Introduction_R2;
        public InputAction @L1 => m_Wrapper.m_Introduction_L1;
        public InputAction @L2 => m_Wrapper.m_Introduction_L2;
        public InputActionMap Get() { return m_Wrapper.m_Introduction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(IntroductionActions set) { return set.Get(); }
        public void SetCallbacks(IIntroductionActions instance)
        {
            if (m_Wrapper.m_IntroductionActionsCallbackInterface != null)
            {
                @ArrowsUp.started -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnArrowsUp;
                @ArrowsUp.performed -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnArrowsUp;
                @ArrowsUp.canceled -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnArrowsUp;
                @ArrowDown.started -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnArrowDown;
                @ArrowDown.performed -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnArrowDown;
                @ArrowDown.canceled -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnArrowDown;
                @A.started -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnA;
                @A.performed -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnA;
                @A.canceled -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnA;
                @ArrowLeft.started -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnArrowLeft;
                @ArrowLeft.performed -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnArrowLeft;
                @ArrowLeft.canceled -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnArrowLeft;
                @ArrowRight.started -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnArrowRight;
                @ArrowRight.performed -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnArrowRight;
                @ArrowRight.canceled -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnArrowRight;
                @X.started -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnX;
                @X.performed -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnX;
                @X.canceled -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnX;
                @Y.started -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnY;
                @Y.performed -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnY;
                @Y.canceled -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnY;
                @B.started -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnB;
                @B.performed -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnB;
                @B.canceled -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnB;
                @Start.started -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnStart;
                @Start.performed -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnStart;
                @Start.canceled -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnStart;
                @Select.started -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnSelect;
                @R1.started -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnR1;
                @R1.performed -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnR1;
                @R1.canceled -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnR1;
                @R2.started -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnR2;
                @R2.performed -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnR2;
                @R2.canceled -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnR2;
                @L1.started -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnL1;
                @L1.performed -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnL1;
                @L1.canceled -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnL1;
                @L2.started -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnL2;
                @L2.performed -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnL2;
                @L2.canceled -= m_Wrapper.m_IntroductionActionsCallbackInterface.OnL2;
            }
            m_Wrapper.m_IntroductionActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ArrowsUp.started += instance.OnArrowsUp;
                @ArrowsUp.performed += instance.OnArrowsUp;
                @ArrowsUp.canceled += instance.OnArrowsUp;
                @ArrowDown.started += instance.OnArrowDown;
                @ArrowDown.performed += instance.OnArrowDown;
                @ArrowDown.canceled += instance.OnArrowDown;
                @A.started += instance.OnA;
                @A.performed += instance.OnA;
                @A.canceled += instance.OnA;
                @ArrowLeft.started += instance.OnArrowLeft;
                @ArrowLeft.performed += instance.OnArrowLeft;
                @ArrowLeft.canceled += instance.OnArrowLeft;
                @ArrowRight.started += instance.OnArrowRight;
                @ArrowRight.performed += instance.OnArrowRight;
                @ArrowRight.canceled += instance.OnArrowRight;
                @X.started += instance.OnX;
                @X.performed += instance.OnX;
                @X.canceled += instance.OnX;
                @Y.started += instance.OnY;
                @Y.performed += instance.OnY;
                @Y.canceled += instance.OnY;
                @B.started += instance.OnB;
                @B.performed += instance.OnB;
                @B.canceled += instance.OnB;
                @Start.started += instance.OnStart;
                @Start.performed += instance.OnStart;
                @Start.canceled += instance.OnStart;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @R1.started += instance.OnR1;
                @R1.performed += instance.OnR1;
                @R1.canceled += instance.OnR1;
                @R2.started += instance.OnR2;
                @R2.performed += instance.OnR2;
                @R2.canceled += instance.OnR2;
                @L1.started += instance.OnL1;
                @L1.performed += instance.OnL1;
                @L1.canceled += instance.OnL1;
                @L2.started += instance.OnL2;
                @L2.performed += instance.OnL2;
                @L2.canceled += instance.OnL2;
            }
        }
    }
    public IntroductionActions @Introduction => new IntroductionActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_ArrowsUp;
    private readonly InputAction m_UI_ArrowDown;
    private readonly InputAction m_UI_A;
    private readonly InputAction m_UI_ArrowLeft;
    private readonly InputAction m_UI_ArrowRight;
    private readonly InputAction m_UI_X;
    private readonly InputAction m_UI_Y;
    private readonly InputAction m_UI_B;
    private readonly InputAction m_UI_Start;
    private readonly InputAction m_UI_Select;
    private readonly InputAction m_UI_R1;
    private readonly InputAction m_UI_R2;
    private readonly InputAction m_UI_L1;
    private readonly InputAction m_UI_L2;
    public struct UIActions
    {
        private @PlayerCtrl m_Wrapper;
        public UIActions(@PlayerCtrl wrapper) { m_Wrapper = wrapper; }
        public InputAction @ArrowsUp => m_Wrapper.m_UI_ArrowsUp;
        public InputAction @ArrowDown => m_Wrapper.m_UI_ArrowDown;
        public InputAction @A => m_Wrapper.m_UI_A;
        public InputAction @ArrowLeft => m_Wrapper.m_UI_ArrowLeft;
        public InputAction @ArrowRight => m_Wrapper.m_UI_ArrowRight;
        public InputAction @X => m_Wrapper.m_UI_X;
        public InputAction @Y => m_Wrapper.m_UI_Y;
        public InputAction @B => m_Wrapper.m_UI_B;
        public InputAction @Start => m_Wrapper.m_UI_Start;
        public InputAction @Select => m_Wrapper.m_UI_Select;
        public InputAction @R1 => m_Wrapper.m_UI_R1;
        public InputAction @R2 => m_Wrapper.m_UI_R2;
        public InputAction @L1 => m_Wrapper.m_UI_L1;
        public InputAction @L2 => m_Wrapper.m_UI_L2;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @ArrowsUp.started -= m_Wrapper.m_UIActionsCallbackInterface.OnArrowsUp;
                @ArrowsUp.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnArrowsUp;
                @ArrowsUp.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnArrowsUp;
                @ArrowDown.started -= m_Wrapper.m_UIActionsCallbackInterface.OnArrowDown;
                @ArrowDown.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnArrowDown;
                @ArrowDown.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnArrowDown;
                @A.started -= m_Wrapper.m_UIActionsCallbackInterface.OnA;
                @A.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnA;
                @A.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnA;
                @ArrowLeft.started -= m_Wrapper.m_UIActionsCallbackInterface.OnArrowLeft;
                @ArrowLeft.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnArrowLeft;
                @ArrowLeft.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnArrowLeft;
                @ArrowRight.started -= m_Wrapper.m_UIActionsCallbackInterface.OnArrowRight;
                @ArrowRight.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnArrowRight;
                @ArrowRight.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnArrowRight;
                @X.started -= m_Wrapper.m_UIActionsCallbackInterface.OnX;
                @X.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnX;
                @X.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnX;
                @Y.started -= m_Wrapper.m_UIActionsCallbackInterface.OnY;
                @Y.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnY;
                @Y.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnY;
                @B.started -= m_Wrapper.m_UIActionsCallbackInterface.OnB;
                @B.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnB;
                @B.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnB;
                @Start.started -= m_Wrapper.m_UIActionsCallbackInterface.OnStart;
                @Start.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnStart;
                @Start.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnStart;
                @Select.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSelect;
                @R1.started -= m_Wrapper.m_UIActionsCallbackInterface.OnR1;
                @R1.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnR1;
                @R1.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnR1;
                @R2.started -= m_Wrapper.m_UIActionsCallbackInterface.OnR2;
                @R2.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnR2;
                @R2.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnR2;
                @L1.started -= m_Wrapper.m_UIActionsCallbackInterface.OnL1;
                @L1.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnL1;
                @L1.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnL1;
                @L2.started -= m_Wrapper.m_UIActionsCallbackInterface.OnL2;
                @L2.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnL2;
                @L2.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnL2;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ArrowsUp.started += instance.OnArrowsUp;
                @ArrowsUp.performed += instance.OnArrowsUp;
                @ArrowsUp.canceled += instance.OnArrowsUp;
                @ArrowDown.started += instance.OnArrowDown;
                @ArrowDown.performed += instance.OnArrowDown;
                @ArrowDown.canceled += instance.OnArrowDown;
                @A.started += instance.OnA;
                @A.performed += instance.OnA;
                @A.canceled += instance.OnA;
                @ArrowLeft.started += instance.OnArrowLeft;
                @ArrowLeft.performed += instance.OnArrowLeft;
                @ArrowLeft.canceled += instance.OnArrowLeft;
                @ArrowRight.started += instance.OnArrowRight;
                @ArrowRight.performed += instance.OnArrowRight;
                @ArrowRight.canceled += instance.OnArrowRight;
                @X.started += instance.OnX;
                @X.performed += instance.OnX;
                @X.canceled += instance.OnX;
                @Y.started += instance.OnY;
                @Y.performed += instance.OnY;
                @Y.canceled += instance.OnY;
                @B.started += instance.OnB;
                @B.performed += instance.OnB;
                @B.canceled += instance.OnB;
                @Start.started += instance.OnStart;
                @Start.performed += instance.OnStart;
                @Start.canceled += instance.OnStart;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @R1.started += instance.OnR1;
                @R1.performed += instance.OnR1;
                @R1.canceled += instance.OnR1;
                @R2.started += instance.OnR2;
                @R2.performed += instance.OnR2;
                @R2.canceled += instance.OnR2;
                @L1.started += instance.OnL1;
                @L1.performed += instance.OnL1;
                @L1.canceled += instance.OnL1;
                @L2.started += instance.OnL2;
                @L2.performed += instance.OnL2;
                @L2.canceled += instance.OnL2;
            }
        }
    }
    public UIActions @UI => new UIActions(this);

    // EditingMap
    private readonly InputActionMap m_EditingMap;
    private IEditingMapActions m_EditingMapActionsCallbackInterface;
    private readonly InputAction m_EditingMap_ArrowsUp;
    private readonly InputAction m_EditingMap_ArrowDown;
    private readonly InputAction m_EditingMap_A;
    private readonly InputAction m_EditingMap_ArrowLeft;
    private readonly InputAction m_EditingMap_ArrowRight;
    private readonly InputAction m_EditingMap_X;
    private readonly InputAction m_EditingMap_Y;
    private readonly InputAction m_EditingMap_B;
    private readonly InputAction m_EditingMap_Start;
    private readonly InputAction m_EditingMap_Select;
    private readonly InputAction m_EditingMap_R1;
    private readonly InputAction m_EditingMap_R2;
    private readonly InputAction m_EditingMap_L1;
    private readonly InputAction m_EditingMap_L2;
    public struct EditingMapActions
    {
        private @PlayerCtrl m_Wrapper;
        public EditingMapActions(@PlayerCtrl wrapper) { m_Wrapper = wrapper; }
        public InputAction @ArrowsUp => m_Wrapper.m_EditingMap_ArrowsUp;
        public InputAction @ArrowDown => m_Wrapper.m_EditingMap_ArrowDown;
        public InputAction @A => m_Wrapper.m_EditingMap_A;
        public InputAction @ArrowLeft => m_Wrapper.m_EditingMap_ArrowLeft;
        public InputAction @ArrowRight => m_Wrapper.m_EditingMap_ArrowRight;
        public InputAction @X => m_Wrapper.m_EditingMap_X;
        public InputAction @Y => m_Wrapper.m_EditingMap_Y;
        public InputAction @B => m_Wrapper.m_EditingMap_B;
        public InputAction @Start => m_Wrapper.m_EditingMap_Start;
        public InputAction @Select => m_Wrapper.m_EditingMap_Select;
        public InputAction @R1 => m_Wrapper.m_EditingMap_R1;
        public InputAction @R2 => m_Wrapper.m_EditingMap_R2;
        public InputAction @L1 => m_Wrapper.m_EditingMap_L1;
        public InputAction @L2 => m_Wrapper.m_EditingMap_L2;
        public InputActionMap Get() { return m_Wrapper.m_EditingMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EditingMapActions set) { return set.Get(); }
        public void SetCallbacks(IEditingMapActions instance)
        {
            if (m_Wrapper.m_EditingMapActionsCallbackInterface != null)
            {
                @ArrowsUp.started -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnArrowsUp;
                @ArrowsUp.performed -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnArrowsUp;
                @ArrowsUp.canceled -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnArrowsUp;
                @ArrowDown.started -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnArrowDown;
                @ArrowDown.performed -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnArrowDown;
                @ArrowDown.canceled -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnArrowDown;
                @A.started -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnA;
                @A.performed -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnA;
                @A.canceled -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnA;
                @ArrowLeft.started -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnArrowLeft;
                @ArrowLeft.performed -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnArrowLeft;
                @ArrowLeft.canceled -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnArrowLeft;
                @ArrowRight.started -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnArrowRight;
                @ArrowRight.performed -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnArrowRight;
                @ArrowRight.canceled -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnArrowRight;
                @X.started -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnX;
                @X.performed -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnX;
                @X.canceled -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnX;
                @Y.started -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnY;
                @Y.performed -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnY;
                @Y.canceled -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnY;
                @B.started -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnB;
                @B.performed -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnB;
                @B.canceled -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnB;
                @Start.started -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnStart;
                @Start.performed -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnStart;
                @Start.canceled -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnStart;
                @Select.started -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnSelect;
                @R1.started -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnR1;
                @R1.performed -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnR1;
                @R1.canceled -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnR1;
                @R2.started -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnR2;
                @R2.performed -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnR2;
                @R2.canceled -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnR2;
                @L1.started -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnL1;
                @L1.performed -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnL1;
                @L1.canceled -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnL1;
                @L2.started -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnL2;
                @L2.performed -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnL2;
                @L2.canceled -= m_Wrapper.m_EditingMapActionsCallbackInterface.OnL2;
            }
            m_Wrapper.m_EditingMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ArrowsUp.started += instance.OnArrowsUp;
                @ArrowsUp.performed += instance.OnArrowsUp;
                @ArrowsUp.canceled += instance.OnArrowsUp;
                @ArrowDown.started += instance.OnArrowDown;
                @ArrowDown.performed += instance.OnArrowDown;
                @ArrowDown.canceled += instance.OnArrowDown;
                @A.started += instance.OnA;
                @A.performed += instance.OnA;
                @A.canceled += instance.OnA;
                @ArrowLeft.started += instance.OnArrowLeft;
                @ArrowLeft.performed += instance.OnArrowLeft;
                @ArrowLeft.canceled += instance.OnArrowLeft;
                @ArrowRight.started += instance.OnArrowRight;
                @ArrowRight.performed += instance.OnArrowRight;
                @ArrowRight.canceled += instance.OnArrowRight;
                @X.started += instance.OnX;
                @X.performed += instance.OnX;
                @X.canceled += instance.OnX;
                @Y.started += instance.OnY;
                @Y.performed += instance.OnY;
                @Y.canceled += instance.OnY;
                @B.started += instance.OnB;
                @B.performed += instance.OnB;
                @B.canceled += instance.OnB;
                @Start.started += instance.OnStart;
                @Start.performed += instance.OnStart;
                @Start.canceled += instance.OnStart;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @R1.started += instance.OnR1;
                @R1.performed += instance.OnR1;
                @R1.canceled += instance.OnR1;
                @R2.started += instance.OnR2;
                @R2.performed += instance.OnR2;
                @R2.canceled += instance.OnR2;
                @L1.started += instance.OnL1;
                @L1.performed += instance.OnL1;
                @L1.canceled += instance.OnL1;
                @L2.started += instance.OnL2;
                @L2.performed += instance.OnL2;
                @L2.canceled += instance.OnL2;
            }
        }
    }
    public EditingMapActions @EditingMap => new EditingMapActions(this);

    // No Controls
    private readonly InputActionMap m_NoControls;
    private INoControlsActions m_NoControlsActionsCallbackInterface;
    private readonly InputAction m_NoControls_Newaction;
    public struct NoControlsActions
    {
        private @PlayerCtrl m_Wrapper;
        public NoControlsActions(@PlayerCtrl wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_NoControls_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_NoControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NoControlsActions set) { return set.Get(); }
        public void SetCallbacks(INoControlsActions instance)
        {
            if (m_Wrapper.m_NoControlsActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_NoControlsActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_NoControlsActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_NoControlsActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_NoControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public NoControlsActions @NoControls => new NoControlsActions(this);
    public interface IGamePlayActions
    {
        void OnArrowsUp(InputAction.CallbackContext context);
        void OnArrowDown(InputAction.CallbackContext context);
        void OnA(InputAction.CallbackContext context);
        void OnArrowLeft(InputAction.CallbackContext context);
        void OnArrowRight(InputAction.CallbackContext context);
        void OnX(InputAction.CallbackContext context);
        void OnY(InputAction.CallbackContext context);
        void OnB(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnR1(InputAction.CallbackContext context);
        void OnR2(InputAction.CallbackContext context);
        void OnL1(InputAction.CallbackContext context);
        void OnL2(InputAction.CallbackContext context);
    }
    public interface IIntroductionActions
    {
        void OnArrowsUp(InputAction.CallbackContext context);
        void OnArrowDown(InputAction.CallbackContext context);
        void OnA(InputAction.CallbackContext context);
        void OnArrowLeft(InputAction.CallbackContext context);
        void OnArrowRight(InputAction.CallbackContext context);
        void OnX(InputAction.CallbackContext context);
        void OnY(InputAction.CallbackContext context);
        void OnB(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnR1(InputAction.CallbackContext context);
        void OnR2(InputAction.CallbackContext context);
        void OnL1(InputAction.CallbackContext context);
        void OnL2(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnArrowsUp(InputAction.CallbackContext context);
        void OnArrowDown(InputAction.CallbackContext context);
        void OnA(InputAction.CallbackContext context);
        void OnArrowLeft(InputAction.CallbackContext context);
        void OnArrowRight(InputAction.CallbackContext context);
        void OnX(InputAction.CallbackContext context);
        void OnY(InputAction.CallbackContext context);
        void OnB(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnR1(InputAction.CallbackContext context);
        void OnR2(InputAction.CallbackContext context);
        void OnL1(InputAction.CallbackContext context);
        void OnL2(InputAction.CallbackContext context);
    }
    public interface IEditingMapActions
    {
        void OnArrowsUp(InputAction.CallbackContext context);
        void OnArrowDown(InputAction.CallbackContext context);
        void OnA(InputAction.CallbackContext context);
        void OnArrowLeft(InputAction.CallbackContext context);
        void OnArrowRight(InputAction.CallbackContext context);
        void OnX(InputAction.CallbackContext context);
        void OnY(InputAction.CallbackContext context);
        void OnB(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnR1(InputAction.CallbackContext context);
        void OnR2(InputAction.CallbackContext context);
        void OnL1(InputAction.CallbackContext context);
        void OnL2(InputAction.CallbackContext context);
    }
    public interface INoControlsActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
